services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: divitrek_db
      POSTGRES_USER: divitrek_user
      POSTGRES_PASSWORD: divitrek_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://divitrek_user:divitrek_password@db:5432/divitrek_db
      API_BASE: http://localhost:8000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
      - "8501:8501"

volumes:
  db_data:


